[project]
name = "wal-g-exporter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3==1.34.74",
    "prometheus-client==0.16.0",
    "psycopg2-binary>=2.9.10",
    "pyinstaller==5.13.2",
    "requests>=2.32.3",
]
